platform :ios, '14.0'

def install_common
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxAppState', '~> 1.6'
  pod 'RxDataSources'
  pod 'RxGesture'
  pod 'WeakMapTable'
  pod 'SwiftLint'
end

target 'shinghaLib' do
  use_frameworks!
  install_common
  pod 'SnapKit', '~> 5.6.0'
  pod 'Alamofire'
end

target 'shinghaLibrary' do
  use_frameworks!
  install_common
end
